### ISSUE TITLE
pxe_config role too slow!

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-pxe_config#14]
Running

$ time ansible-playbook install.yml --tags=pxe

takes 10 mins here.. We now have slightly under 200 compute nodes, and most of the time goes in various loops over nodes. Apparently ansible does a new ssh connection for every node in the lists, since they take something like ~1s / node (and yes, we have pipelining, ControlPersist and all that, presumably it would be even worse without it). I wonder if it would be possible to restructure it so it goes faster somehow..

**Comment by A1ve5** [comment]
Yes. In fact that issue has been somehow introduced here (not very descriptive, I know) https://github.com/CSC-IT-Center-for-Science/fgci-ansible/issues/29
The idea would be refactoring those roles into 1 or 2 and in more sensible way.
That's a big task that requires a lot of thought before we break anything...

**Comment by jabl** [comment]
With the above pull #15 the time is roughly cut in half. The remaining big time wasters seem to be the create_pxe_boot_data and "copy over kickstart file" tasks. At least for create_pxe_boot_data I have a plan to instead generate, say, a JSON file, and then modify boot.py to lookup the data for the node from that JSON file instead of looking for a file-per-node.

**Comment by jabl** [comment]
Yay, with pull #15 (already merged) + pull #16 , pull #17 , https://github.com/CSC-IT-Center-for-Science/ansible-role-pxe_bootstrap/pull/4, and pull #18 , the time for "ansible-playbook install.yml --tags=pxe" has dropped to ~3m40s.

The remaining ansible task that takes a lot of time here is the final one, "copy over kickstart file". This could certainly be improved a lot too, since there are only a few kickstart profiles, but the task still loops over all nodes. Any idea how one could accomplish instead looping over kickstart profiles, or something like that?

**Comment by martbhell** [comment]
Perhaps if we somehow only call the first host in each group? I've been trying [1](https://github.com/CSC-IT-Center-for-Science/ansible-role-pxe_config/tree/faster_kickstart_profile_template) to put a [0] in a few places without luck. Maybe one way would be to get a list of all the children groups of pxe_bootable_nodes and then go from there.

groups.pxe_bootable_nodes only has the list of all the nodes in all the children groups of pxe_bootable nodes. It's not in {{ groups }} either.

https://github.com/ansible/ansible/issues/16026 seems to suggest we should make our own inventory script - so probably no point in waiting for this to happen in ansible. Perhaps one could use set_facts in some way to create a better list?

**Comment by martbhell** [comment]
Here is an example to just output the child groups out of a group. The inventory script needs to output it in json and I anyway doubt one can use a different inventory script for one task. Unless maybe one calls the script directly and registers the output in a variable and then use that variable

https://gist.github.com/martbhell/7266d7b1e4e1be1ebbd3ed5d6fe3216f

**Comment by martbhell** [comment]
OK. I got something pretty much working in a separate branch [1](https://github.com/CSC-IT-Center-for-Science/ansible-role-pxe_config/blob/custom_inventory/files/custom-inventory.py) which reduces the "copy over kickstart file" to just three tasks (one per group in pxe_bootable_nodes). Quite ugly - but this way one doesn't have to define another list with the kickstart files or group of one host per group.

**Comment by martbhell** [comment]
OK, I have merged this final improvement into master now. By default the role still uses the old style which loops over every host in pxe_bootable_nodes. To use the new faster style set {{ hosts_file_use_custom_inventory }} to true and it will call the custom-inventory.py script with some arguments, get one host per ansible group back as  JSON, which we then write as facts and finally we loop over that fact instead of pxe_bootable_nodes. Phew.

I'd like to keep this issue open until @jabl have tried it and says if it works for them too. As said, the custom-inventory.py is a real work of art(tm) and I'm a bit hesitant to enable it by default without input from someone who is more experienced with python :)

**Comment by A1ve5** [comment]
@jabl, have you had the chance to test this?
Moving to "Review"

**Comment by jabl** [comment]
I'm on holiday until 14.8, will look at it then.

**Comment by jabl** [comment]
Yeah, seems to work. Setting hosts_file_use_custom_inventory to True and

time ansible-playbook install.yml --tags=pxe

ran in 2m10s.

**Comment by martbhell** [comment]
Great! I'll go ahead and close this issue then. For reference - is the 2m10s also with 200 nodes and 100 forks in ansible.cfg?

**Comment by jabl** [comment]
No, we have a lot more than 200 nodes (still running ex-Vuori to keep enough heat load in the Pohja machine room). Let see...

<pre><code>
# nodeattr -n pxe_bootable_nodes|wc -l
613
</code></pre>

(this is the nodeattr tool from the genders package, using the genders file generated by ansible-role-pdsh-machines genders branch)

Edit: Oh, and yes, with forks=100 in ansible.cfg.

**Comment by jabl** [comment]
Oh, BTW, there was a mention of some issue related to this at the last weekly meeting. Let me copy-paste something...

<pre>
Somebody: Every time I run "sh tools/pullReqs.sh", one line disappears in file roles/ansible-role-pxe_config/tasks/redhat.yml:
 - name: grab a list of hosts (one per child group in {{ hosts_file_group_to_populate }}) using custom-inventory.py
  command: python {{ role_path }}/files/custom-inventory.py --single --json --group {{ hosts_file_group_to_populate }} --inventory {{ hosts_file_inventory_location }}
  register: reg_inventory
  changed_when: False
  delegate_to: localhost
  always_run: True
There should be "become: false" at the end. This creates an error when running ansible-playbook install.yml.
....
Somebody: We found out with Luis that adding the line manually takes care of the error, but that fix is not permanent.
tiggi: there is a "become: false" in the head of the git repo
JanneBlomqvist: You need to tag a new version, and update requirements.yml in fgci-ansible repo.
tiggi: so it's probably waiting for a release
tiggi: I'll poke Guldmyr to do that 
</pre>

**Comment by martbhell** [comment]
So we went down from 3 seconds per node to ~0.212s ( 600s/200nodes vs 130s/613nodes ). Very nice :)

I'll make a release.
