### ISSUE TITLE
custom_inventory.py script doesn't work with nested groups

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-pxe_config#26]
So we have in our inventory something like 

[compute:children]
computeopteron
compute-1disk
compute-2disks
compute-4disks

[pxe_bootable_nodes:children]
compute
...

With this kind of inventory, we get only one kickstart for all compute nodes, instead of separate kickstarts for the opteron, {1,2,4}disk node types.

**Comment by martbhell** [comment]
Ah thanks! I get to play with some more python next week :)

**Comment by martbhell** [comment]
This exercise is expanding my python skills so it might take a while.

As a workaround, would it work for you guys to put the computeopteron etc directly in [pxe_bootable_nodes] and as children of [compute]?

**Comment by martbhell** [comment]
Okay, an update is now in master. I'll update the devel branch in fgci-ansible with the new role version and do some further testing. At least travis looks happy.

The change to the custom-inventory.py can be seen here https://github.com/CSC-IT-Center-for-Science/ansible-role-pxe_config/blob/master/files/custom-inventory.py#L89-L108

Unfortunately I also made some changes (to remove errors from pylint) so it's not so readable what I actually changed just by looking at diffs. But the hilight in the URL above should point to the important parts.

**Comment by martbhell** [comment]
Looks OK on our test system. Could you check if it's better for your cluster now @jabl ?

**Comment by jabl** [comment]
Seems to work, yes!

**Comment by martbhell** [comment]
Thanks, closing this issue.
