### ISSUE TITLE
Create /etc/grid-security on kickstart

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-pxe_config#3]
https://github.com/CSC-IT-Center-for-Science/ansible-role-pxe_config/blob/master/templates/kickstart.cfg

This is so one can scp in the /etc/grid-security host certificates before running the grid.yml

Another way would be to have users copy the certificates into fgci-ansible/certificates/ (gitignored) and then have grid.yml mkdir and copy in the files.

**Comment by tiggi** [comment]
/etc/grid-security gets created when you install the CA packages.

**Comment by martbhell** [comment]
CA packages require a repo with the CA packages and the idea is that we have as much as possible in ansible and not in the provisioning tool. Maybe this is an exception?

**Comment by A1ve5** [comment]
Is this still needed?

**Comment by martbhell** [comment]
Is something creating the directory before we run grid.yml?

**Comment by A1ve5** [comment]
before running ansible-role-arc-frontend (where the hostcert and hostkey files are copied) grid.yml have ansible-role-arc-client. In this one fetch-crl is installed and will create the /etc/grid-security/ folder.

fetch-crl-3.0.17-1.el7.noarch : Downloads Certificate Revocation Lists
Repo        : epel
Matched from:
Filename    : /etc/grid-security/

Closing it.
