### ISSUE TITLE
ansible 2.4 and inventory and the custom_inventory is broken

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-pxe_config#36]
The custom_inventory script broken with ansible 2.4

The first (of many errors):
<pre>
["Traceback (most recent call last):", "  File \"/ansible-role-pxe_config/files/custom-inventory.py\", line 22, in <module>", "    from ansible.inventory import Inventory", "ImportError: cannot import name Inventory"]
</pre>

After fixing above one will stumble onto VariableManager, new/different arguments to classes, classes have changed names.. And then I stopped.

https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/manager.py might be the best place to figure out how to use it.

**Comment by martbhell** [comment]
Had a bit more look.
Looks like quite many changes are needed :)
Maybe what we use this script for (print one host per child group in one or many ansible groups of groups...) is now fixed and easy to do?? =)

**Comment by tiggi** [comment]
Fixed in PR #37
