### ISSUE TITLE
.local TLD for internal network not a good idea

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-pxe_config#4]
It's considered a bad idea to use made-up TLD's, even for stuff not visible to the public internet.

E.g. CA's  will refuse to generate certs and browsers will refuse to connect to such addresses;

https://cabforum.org/internal-names/

Additionally, .local, in particular, is reserved for multicast DNS (mDNS)/zeroconf/bonjour. Due to this, it's conceivable that resolvers will special-case .local. See

https://tools.ietf.org/html/rfc6762

https://en.wikipedia.org/wiki/.local

Best practice seems to be to use a subdomain of the registered domain. The subdomain itself doesn't need to be visible to the outside world in any way. E.g. for a site "clustername.someuni.fi" one could use "int.clustername.someuni.fi".

In tests/redhat.yml .local is hardcoded. So maybe something like "int.{{ siteDomain }}" could work instead, if siteDomain (from the hosts file) is "visible" in the role?

**Comment by martbhell** [comment]
Thanks for this issue report. 
We just replicated the addresses in the aesyle test cluster.
Let's change them.

Some comments on the report:
- .local host entries are created in **tasks**/redhat.yml in pxe_config ansible role
- I grepped through the fgci-ansible repo with all the requirements pulled and could not find .local addresses referenced anywhere else - so it should be fairly safe to not create them anymore.
- siteDomain is a variable defined in group_vars/all/all.yml - so yes, this is available to be used by roles. This variable should not be set in the hosts file.
- p.s. there's also a fact called ansible_domain - but as the compute nodes currently do not have a domain name (see hostname -f on a compute node) we can't use that.

There's also -ib addresses being populated into /etc/hosts. Are they ok?

So in the end you'd like something like this?

<pre>
{{ inventory_hostname }}.{{ siteDomain }}
{{ inventory_hostname }}.ib.{{ siteDomain }}
</pre>

Which with our hosts file looking like this:

<pre>
[compute]
io1 ip_address=10.1.100.1 mac_address=00:MAC pxe_name=io1 ib_ip_addr=10.2.100.1
io2 ip_address=10.1.100.2 mac_address=00:MAC pxe_name=io2 ib_ip_addr=10.2.100.2
io3 ip_address=10.1.100.3 mac_address=00:MAC pxe_name=io3 ib_ip_addr=10.2.100.3
</pre>

Should turn them into:

<pre>
io1.fgci.csc.fi
io2.fgci.csc.fi
</pre>

and

<pre>
io1.ib.fgci.csc.fi
io2.ib.fgci.csc.fi
</pre>

We could also remove the .local addresses if they are not desired.
At least on io test cluster I can already do "ping io1.fgci.csc.fi" even though that is not specifically in the hosts file.
Bare in mind that if we make these changes to the ansible roles we will not in the role remove the old .local entries. You'll have to clean those out yourselves.

**Comment by jabl** [comment]
Yes, indeed siteDomain is defined in group_vars/all/all.yml, like you said. Sorry for the confusion.

Another thing, in all.yml there's also dhcp_common_domain, should that be the same, or is there some reason to have different values there?

As for the hostnames, I think it'd be cleaner with something like

```
{{ inventory_hostname }}.int.{{ siteDomain }}
{{ inventory_hostname }}-ib.int.{{ siteDomain }}
```

I.e. put the internal hostnames on an internal subdomain, rather than having the "real domain" contain different stuff depending on whether one looks at it from the outside or inside.

As for the ib addresses, I don't have any big opinion whether it should be a separate .ib. domain or whether they should be in the same domain as the eth interfaces, just named -ib as now. Maybe -ib, then one can just use the short names and not fqdn's when working with them.

**Comment by martbhell** [comment]
I think this is OK now - ran the new role on io-install and got these new entries to the bottom of the /etc/hosts file (existing entries were not touched and it is still idempotent):

<pre>
10.1.100.1 io1.int io1.int.fgci.csc.fi
10.1.100.2 io2.int io2.int.fgci.csc.fi
10.1.100.3 io3.int io3.int.fgci.csc.fi
10.1.100.4 io4.int io4.int.fgci.csc.fi
10.1.100.5 gpu.int gpu.int.fgci.csc.fi
10.1.1.4 io.int io.fgci.csc.fi.int.fgci.csc.fi
10.1.1.5 io-nfs.int io-nfs.int.fgci.csc.fi
</pre>

If you could confirm that it's OK also for you @jabl that would be great.

**Comment by martbhell** [comment]
I see now that it adds "io1.int io1.int.fgci.csc.fi" - should we also remove the io1.int address?

**Comment by jabl** [comment]
Ah, I think we'd rather use the shortest possible names for the non-fqdn ones. I.e. something like

```
10.1.100.1 io1 io1.int.fgci.csc.fi
10.2.100.1 io1-ib io1-ib.int.fgci.csc.fi
```

**Comment by martbhell** [comment]
The shortest form were not touched by this change, they are added by an earlier task.
Added the io1-ib.int.fgci.csc.fi style addresses in 96956ad56f3e693f6309578e2b01281a5f1f1864

**Comment by martbhell** [comment]
<pre>Another thing, in all.yml there's also dhcp_common_domain, should that be the same, or is there some reason to have different values there?
</pre>

maybe @A1ve5  could comment on this? The dhcp_common_domain variable is also used by the ansible-role-dhcp_server

**Comment by A1ve5** [comment]
I see no problem on using the same

**Comment by martbhell** [comment]
OK. Closing this issue now as the .local have been removed and the .int have been added.

**Comment by jabl** [comment]
There's still a bit of strangeness. I cleaned out /etc/hosts on the install node and ran the playbook, now /etc/hosts contains stuff like (for pe01, other nodes similar):

10.10.100.1 pe01 pe01
...
10.10.100.1 pe01.int.triton.aalto.fi
...
10.11.100.1 pe01-ib pe01-ib.int.triton.aalto.fi

Shouldn't the non-ib addresses be done in a similar fasion, e.g. instead of the two first lines above one would have

10.10.100.1 pe01 pe01.int.triton.aalto.fi

**Comment by jabl** [comment]
Oh, I see what it is. Patch coming in a few minutes..
